#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
A="$ROOT/third_party/aevum"

grep -q '4.20.49-alpha-v99.39-aevum-apple-midout-tailmul-localpair' "$ROOT/include/core/Version.hpp"
grep -q 'AEVUM_VERSION ?= v0.3.34' "$A/Makefile"

grep -q 'buildMonolithicOpenCLSource' "$A/src/KernelCompiler.cpp"
grep -q 'clBuildProgram' "$A/src/KernelCompiler.cpp"
grep -q 'AEVUM_APPLE_OPENCL12=1' "$A/src/KernelCompiler.cpp"
grep -q 'Apple OpenCL pipeline retry' "$A/src/KernelCompiler.cpp"
grep -q -- '-cl-opt-disable' "$A/src/KernelCompiler.cpp"

grep -q '__OPENCL_C_VERSION__ < 200' "$A/src/cl/base.cl"
grep -q 'get_local_size(0) / 2 > WAVEFRONT' "$A/src/cl/base.cl"
! grep -Fq 'shufl32((local F2 *) lds, (local F2 *) u' "$A/src/cl/fftbase.cl"
grep -Fq 'shufl32((local F2 *) lds, (F2 *) u' "$A/src/cl/fftbase.cl"

grep -q 'AEVUM_READY_STORE' "$A/src/cl/carryfused.cl"
grep -q 'AEVUM_READY_LOAD' "$A/src/cl/carryfused.cl"
grep -q 'atomic_xchg((volatile global uint \*) (ptr), 1u)' "$A/src/cl/carryfused.cl"
grep -q 'atomic_add((volatile global uint \*) (ptr), 0u)' "$A/src/cl/carryfused.cl"
grep -q 'apple_opencl12_kernel_matrix_syntax.sh' "$A/Makefile"

grep -q 'config.try_emplace("IN_WG", "64")' "$A/src/Gpu.cpp"
grep -q 'config.try_emplace("OUT_WG", "64")' "$A/src/Gpu.cpp"
grep -q 'config.try_emplace("MIDDLE_IN_LDS_TRANSPOSE", "1")' "$A/src/Gpu.cpp"
grep -q 'config.try_emplace("MIDDLE_OUT_LDS_TRANSPOSE", "1")' "$A/src/Gpu.cpp"
# LDS remains in the production middle transforms.
grep -q 'local Z61 lds' "$A/src/cl/fftmiddlein.cl"
grep -q 'middleShuffle(lds, u, IN_WG, IN_SIZEX)' "$A/src/cl/fftmiddlein.cl"
grep -q 'local Z61 lds' "$A/src/cl/fftmiddleout.cl"
grep -q 'middleShuffle(lds, u, OUT_WG, OUT_SIZEX)' "$A/src/cl/fftmiddleout.cl"

grep -q 'AEVUM_APPLE_SPLIT_FFTP' "$A/src/cl/fftp.cl"
grep -q 'fftP31Apple' "$A/src/cl/fftp.cl"
grep -q 'fftP61WeightScalarApple' "$A/src/cl/fftp.cl"
grep -q 'fftP61WidthRadixApple' "$A/src/cl/fftp.cl"
# The original non-Apple fftP remains present behind the Apple-specific branch.
grep -q 'KERNEL(G_W) fftP(P(T2) out, CP(Word2) in, Trig smallTrig)' "$A/src/cl/fftp.cl"

grep -q '#if defined(__APPLE__)' "$A/src/Gpu.cpp"
grep -q '#if defined(__APPLE__) && !defined(CUDA_BACKEND)' "$A/src/KernelCompiler.cpp"

grep -q 'size_t prepared_count = 0;' "$A/src/EngineApi.cpp"
grep -q 'getOpenCLCVersion' "$A/src/clwrap.cpp"

python3 "$A/tests/apple_gf61_scalar_mapping_test.py"
python3 "$A/tests/apple_gf61_width_staging_test.py"
python3 "$A/tests/apple_gf61_middlein_staging_test.py"

grep -q 'fftMiddleInGF61LoadScalarApple' "$A/src/cl/fftmiddlein.cl"
grep -q 'fftMiddleInGF61Mul2FactorScalarApple' "$A/src/cl/fftmiddlein.cl"
grep -q 'fftMiddleInGF61ApplyScalarApple' "$A/src/cl/fftmiddlein.cl"
! grep -q 'fftMiddleInGF61LoadMul2Apple' "$A/src/cl/fftmiddlein.cl"
grep -q 'fftMiddleInGF61TransposeApple' "$A/src/cl/fftmiddlein.cl"
grep -q 'kfftMidInGF61LoadScalarApple' "$A/src/Gpu.cpp"
grep -q 'kfftMidInGF61Mul2FactorScalarApple' "$A/src/Gpu.cpp"
grep -q 'kfftMidInGF61ApplyScalarApple' "$A/src/Gpu.cpp"
grep -q 'kfftMidInGF61TransposeApple' "$A/src/Gpu.cpp"
grep -Fq 'config["INPLACE"] = "0";' "$A/src/Gpu.cpp"
grep -q 'forcing TAIL_KERNELS=3 (double-wide, two kernels)' "$A/src/Gpu.cpp"
grep -Fq 'config["TAIL_KERNELS"] = "3";' "$A/src/Gpu.cpp"
grep -q 'tailSquareZeroGF61' "$A/src/cl/tailsquare.cl"
grep -q 'local GF61 lds\[2 \* LDS_BYTES / sizeof(GF61)\]' "$A/src/cl/tailsquare.cl"
python3 "$A/tests/apple_gf61_tail_two_kernel_policy_test.py"
grep -q 'tailSquareZeroGF61LoadApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareZeroGF61FftRadixApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareZeroGF61FftTwiddleApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareZeroGF61FftShuffleApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareZeroGF61FftFinalApple' "$A/src/cl/tailsquare.cl"
grep -q 'appleTailZeroGF61BankIndex' "$A/src/cl/tailsquare.cl"
grep -q 'srcI = (logical / f) % RADIX' "$A/src/cl/tailsquare.cl"
grep -q 'BUF(bufAppleTailZeroGF61, fft.NTT_GF61 ? 8 \* SMALL_H : 0)' "$A/src/Gpu.cpp"
grep -q 'tailSquareZeroGF61ReverseGlobalApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareZeroGF61PairApple(P(GF61) scratch, Trig smallTrig, u32 bank)' "$A/src/cl/tailsquare.cl"
grep -Fq 'ktailSquareZeroGF61PairApple(bufAppleTailZeroGF61, bufTrigH, 1u);' "$A/src/Gpu.cpp"
! grep -Fq 'ktailSquareZeroGF61PairApple.setFixedArgs(1, bufTrigH);' "$A/src/Gpu.cpp"
grep -q 'tailSquareZeroGF61WriteDirectApple' "$A/src/cl/tailsquare.cl"
grep -Fq 'K(ktailSquareZeroGF61WriteDirectApple,   "tailsquare.cl", "tailSquareZeroGF61WriteDirectApple",   SMALL_H' "$A/src/Gpu.cpp"
grep -Fq 'ktailSquareZeroGF61WriteDirectApple(*out, bufAppleTailZeroGF61, 0u, 0u);' "$A/src/Gpu.cpp"
grep -Fq 'ktailSquareZeroGF61WriteDirectApple(*out, bufAppleTailZeroGF61, SMALL_H, (fft.shape.middle / 2u) * SMALL_H);' "$A/src/Gpu.cpp"
! grep -q 'writeTailFusedValue(value' "$A/src/cl/tailsquare.cl"
! grep -q 'KERNEL(G_H) tailSquareZeroGF61WriteApple' "$A/src/cl/tailsquare.cl"
grep -q 'bufAppleTailZeroGF61' "$A/src/Gpu.cpp"
python3 "$A/tests/apple_gf61_tailzero_staging_test.py"
python3 "$A/tests/apple_gf61_maintail_staging_test.py"
grep -q 'tailSquareGF61LoadScalarApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareGF61ReverseCrossApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareGF61PairApple' "$A/src/cl/tailsquare.cl"
grep -q 'tailSquareGF61ApplePlaceholder' "$A/src/cl/tailsquare.cl"
grep -Fq 'ktailSquareGF61LoadScalarApple(*out, *in);' "$A/src/Gpu.cpp"
grep -Fq 'Buffer<double> *next = current == out ? in : out;' "$A/src/Gpu.cpp"
! grep -q 'bufAppleTailGF61' "$A/src/Gpu.cpp"
grep -q 'fftWGF61ApplePlaceholder' "$A/src/cl/fftw.cl"
grep -q 'fftWGF61LoadScalarApple' "$A/src/cl/fftw.cl"
grep -q 'fftWGF61WidthRadixApple' "$A/src/cl/fftw.cl"
grep -q 'fftWGF61TwiddleShuffle1Apple' "$A/src/cl/fftw.cl"
grep -q 'fftWGF61WidthFinalApple' "$A/src/cl/fftw.cl"
grep -q 'tailMulGF61PairLocalApple' "$A/src/cl/tailmul.cl"
! grep -q 'tailMulGF61ReverseStockApple' "$A/src/cl/tailmul.cl"
! grep -q 'tailMulGF61PairStockApple' "$A/src/cl/tailmul.cl"
! grep -q 'tailMulGF61PairDirectApple' "$A/src/cl/tailmul.cl"
grep -q 'AEVUM_APPLE_OPENCL12' "$A/src/cl/fft8.cl"
grep -q 'Inline the exact GF31 fft4Core body twice' "$A/src/cl/fft8.cl"
grep -q 'bufAppleTailMulGF61' "$A/src/Gpu.h"
grep -q 'vector<Word> first = readOut(buf);' "$A/src/Gpu.cpp"
grep -q 'vector<Word> second = readOut(buf);' "$A/src/Gpu.cpp"
grep -q 'if (first == second)' "$A/src/Gpu.cpp"
! sed -n '/#if defined(__APPLE__)/,/#else/p' "$A/src/Gpu.cpp" | grep -q 'sum64(bufSumOut, N, buf)'
python3 "$A/tests/apple_readchecked_double_sync_test.py"
python3 "$A/tests/apple_queue_marker_flush_test.py"
grep -Fq '#if defined(__APPLE__)' "$A/src/Queue.cpp"
grep -Fq '::flush(get());' "$A/src/Queue.cpp"
python3 "$ROOT/tests/apple_strict_smoke_source_test.py"
grep -Fq 'kfftWGF61LoadScalarApple(*out, *in);' "$A/src/Gpu.cpp"
grep -Fq 'Buffer<double>* alternate = in;' "$A/src/Gpu.cpp"
! grep -q 'bufAppleFftWGF61' "$A/src/Gpu.cpp"
python3 "$A/tests/apple_gf61_fftw_staging_test.py"
python3 "$A/tests/apple_gf61_tailmul_staging_test.py"
grep -q 'fftMiddleOutGF61CoreApple' "$A/src/cl/fftmiddleout.cl"
grep -q 'fftMiddleOutGF61WriteApple' "$A/src/cl/fftmiddleout.cl"
grep -q 'fftMiddleOutGF61ApplePlaceholder' "$A/src/cl/fftmiddleout.cl"
grep -Fq 'kfftMidOutGF61CoreApple(bufAppleTailMulGF61, *in, bufTrigM);' "$A/src/Gpu.cpp"
grep -Fq 'kfftMidOutGF61WriteApple(*out, bufAppleTailMulGF61);' "$A/src/Gpu.cpp"
python3 "$A/tests/apple_gf61_middleout_staging_test.py"
echo 'PrMers v99.39 Apple GF61 middle-out and exact local-pair tailMul source audit passed'   
